workflows:
  android-local-apk:
    name: Android Local APK Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    triggering:
      events:
        - push
      cancel_previous_builds: true

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - keystore_credentials   # Contains KEYSTORE_FILE, KEYSTORE_PASSWORD, KEYSTORE_KEY_PASSWORD

    scripts:
      - name: Setup Keystore
        script: |
          echo "$KEYSTORE_FILE" | base64 --decode > /tmp/keystore.jks
          cat > "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=upload
          storeFile=/tmp/keystore.jks
          EOF

      - name: Flutter Clean & Get Packages
        script: |
          cd $CM_BUILD_DIR
          flutter clean
          flutter pub get

      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

